# If all inputs are in a single file, simply specify input_file
in_data: ''  # Empty string

# patterns lists the types where there are multiple files
patterns:
    - '/pscratch/sd/w/wcmca1/scream-cess-healpix/data4TE/Updated/ifs_tco3999_rcbmf_PT1H/ifs_tco3999_rcbmf_ivt_hp7_PT1H.????????.nc'

# pattern match specifies the pattern that changes between each file
pattern_match: '(PT1H.\d{6})'  # Regular expression

# input_list specified the name of the text file 
in_data_list: '/pscratch/sd/b/beharrop/kmscale_hackathon/hackathon_pre/ifs_tco3999_rcbmf_tracking/ifs_tco3999_rcbmf.input_pr_ws.txt'  # Placeholder for dynamic content

# a static file can be used for time invariant variables like elevation that may need to be specified, but exist in a single file
# this file gets appended to each line within input_list
static_file: ''