# shortname <string>
# Specify a name to use for naming files (required)
shortname: 'v3.LR.F2010.prescribedCRE_1H_allSWdiffs'

# output_dir <string>
# Specify the path to save files to (required)
output_dir: '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/post/atm/native/tracking2/'

# --in_data <string> ""
# A list of input data files in NetCDF format, separated by semicolons.
in_data: ''

#  --in_data_list <string> ""
# A text file containing the --in_data argument for a sequence of processing
# operations (one per line). When parallelization is enabled, the list of data
# files are distributed as equally as possible among available processors.
# If multiple data_lists are needed for different steps, they can be specified as 
# in_data_list_step1, in_data_list_step2, etc.
# If in_data_list is in steps, then patterns, pattern_match, and static_file
# require corresponding steps.
in_data_list: '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/post/atm/native/tracking2/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.input.txt'
#in_data_list_step1: '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/post/atm/native/tracking2/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.input1.txt'
#in_data_list_step2: '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/post/atm/native/tracking2/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.input2.txt'
#in_data_list_step3: '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/post/atm/native/tracking2/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.input3.txt'

# --in <string> ""
# The input nodefile (typically output from from DetectNodes).
in: ''

# --in_nodefile <string> ""
# The filename of the input nodefile (typically output from
# DetectNodes or StitchNodes).
in_nodefile: ''

#  --in_nodefile_type <string> ["SN"] [DN|SN]
# The type of nodefile indicated by --in_nodefile: "DN" if from DetectNodes
# or "SN" if from StitchNodes.
in_nodefile_type: ''

#  --in_list <string> ""
# A text file containing a list of input data files.
in_list: ''

#  --in_connect <string> ""
#A connectivity file that describes the unstructured grid.
in_connect: '/qfs/people/harr152/TempestExtremes/connectivity_files/connect_CSne30pg2.txt'

#  --diag_connect <bool>
# When the data is on a structured grid, consider grid cells to be connected in
# the diagonal (across the vertex).
diag_connect: ''

# The following output stuff is set dynamically by the script... consider removing

#  --out <string> ""
# The output nodefile to write from the detection procedure.
# Used when --in_data is specified.
out: ''

#  --out_file_list <string> ""
# A text file containing an equal number of lines to --in_data_list specifying
# the output nodefiles from each input datafile.
out_file_list: ''

# --out_list <string> ""
# A text file containing, one per line, a list of output NetCDF files corresponding to the input files specified in --in_list or --in_data_list
out_list: ''

# --out_data_list <string> ""
# A list of output data files, of the corresponding output for each file of --in_data_list
out_data_list: ''

# --out_data <string> ""
# The output data file
out_data: ''

# The following arguments are not inputs directly to TE binaries

# patterns lists the types where there are multiple files
patterns:
    - '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/archive/atm/hist/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.eam.h1.????-??-??-00000.nc'
#pattern_step1:
#    - '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/archive/atm/hist/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.eam.h1.????-??-??-00000.nc'
#pattern_step2:
#    - '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/archive/atm/hist/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.eam.h1.????-??-??-00000.nc'
#pattern_step3:
#    - '/compyfs/harr152/E3SMv3/F2010/v3.LR.F2010.prescribedCRE_1H_allSWdiffs/archive/atm/hist/v3.LR.F2010.prescribedCRE_1H_allSWdiffs.eam.h1.????-??-??-00000.nc'

# pattern match specifies the pattern that changes between each file
pattern_match: '(eam.h1.\d{4}-\d{2}-\d{2})'  # Regular expression
#pattern_match_step1: '(eam.h1.\d{4}-\d{2}-\d{2})'
#pattern_match_step2: '(eam.h1.\d{4}-\d{2}-\d{2})'
#pattern_match_step3: '(eam.h1.\d{4}-\d{2}-\d{2})'

# a static file can be used for time invariant variables like elevation that may need to be specified, but exist in a single file
# this file gets appended to each line within input_list
static_file: ''
#static_file_step1: ''
#static_file_step2: ''
#static_file_step3: ''

# the crs file contains metadata for the healpix grid and can be appended during file cleanup
crs_file: ''

# file cleanup arguments
do_file_cleanup: false

# do_append_crs - appends healpix metadata to all files
do_append_crs: false

# do_unify_dimensions - if both cell and ncol are created, then rename ncol to cell
do_unify_dimensions: false

# do_open_permissions - opens up read permissions for all users
do_open_permissions: false